### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpm-js#10]
Distilled from discussions at http://pad.okfn.org/p/labs-data-packages
## Plan

We will converge on https://github.com/okfn/dpm (merge existing dpm2 into here ...)
### Stage 1:
- [x] merge dpm2 with this repo - #9 
- [x] dpm init - #4 
- [x] dpm install {name or url}   # just from url or git url ... - #3 
- [ ] support for datapackage.json style requirements in a normal project
### Stage 2
- [ ] web view
- [ ] web create / init  online
- [ ] dpm view  
### Stage 3
- [ ] registry - #5 
- [ ] dpm publish - #2 
- [ ] dpm install supports registry
### Stage 4
- [ ] validate
  - need schemas - see https://github.com/dataprotocols/schemas
### Other changes / decisions
- Reuse npm conceptually but probably not literally
- datapackage.json rather than package.json
  - This is different so name should be different
  - What we have now
  - Different makes it easier to identify e.g. on github
  - we are not directly reusing npm so not a problem there (cf component.io stuff)
- Semi-deprecate: datapackage.js
- Copy over everything from dpm2 into dpm
- Maybe split out later to:
  - dpm-init
  - dpm-install
  - ...

---
## What We Want - Overview

Commands (in rough order of priority)
- init (create)
  - (??) adddata (add a data file to the data package)
- install
- install with deps
- view
- publish [depends on registry]
- validate [validate a data file against schema]

Note we want both command line and web so provide library commands that support web stuff (but dpm will focus on the command line tool)
### Registry

To do nice install "medium-term" we want a registry but not an immediate (new few weeks) priority. Registry / catalog needs:
- post (publish)
- get (install)
- ownership

**Comment by pwalsh** [comment]
@rgrp I'm thinking of closing this, as very old. Are there things here we def. want to capture in more specific issues?
